### ISSUE TITLE
Unhandled Exception when Navigating

### ISSUE THREAD

**Issue by Minmoose** [ZeroElectric/QuotumMediaPlayer#1]
Find out what caused this Unhandled Exception. Seems to be something to do with Binding?

System.InvalidCastException: Unable to cast object of type 'Quotum.MediaPlayer.ArtistObject' to type 'Quotum.MediaPlayer.AlbumObject'.
   at Quotum.Views.AlbumsView.AlbumsView_obj3_Bindings.SetDataRoot(Object newDataRoot)
   at Quotum.Views.AlbumsView.AlbumsView_obj3_Bindings.ProcessBindings(Object item, Int32 itemIndex, Int32 phase, Int32& nextPhase)

**Comment by Minmoose** [comment]
This is caused when on the Artist View and clicking the Albums nav button before Artist View has loaded fully 

[CrashLog 7‎-12‎-‎2021_2-‎‎00-‎‎14.txt](https://github.com/ZeroElectric/QuotumMediaPlayer/files/6799267/CrashLog.7.-12.-.2021_2-.00-.14.txt)

**Comment by Minmoose** [comment]
I got this Exception today:

```
Trace Message: Unhandled Exception
Exception Message: Specified cast is not valid.
HResult: -2147467262
----- StackTrace ----- 



----- StackTrace ----- 
```

I think this happens if the user has ever opened the Artist View, I think this has something to do with the GeneralCollection where it is still filled with ArtistObject's and when we Nav to Albums View the x:Bind causes an Exception?

**Comment by Minmoose** [comment]
Fixed by clearing GeneralCollection and pushing albums to GeneralCollection

**Comment by Minmoose** [comment]
> I think this happens if the user has ever opened the Artist View, I think this has something to do with the GeneralCollection where it is still filled with ArtistObject's and when we Nav to Albums View the x:Bind causes an Exception?

This was correct, fixed by clearing GeneralCollection and pushing albums to GeneralCollection before the View is loaded, also seems to have reduced the hitch that happens when Albums View loads.
